### ISSUE TITLE
build failed if storage enabled but contract example disabled

### ISSUE THREAD

**Issue by prudnitskiy** [takama/caldera#26]
If service have storage enabled, but API contract example disabled - bootstrap will fail, even if API gateway completely disabled.

Error:
```+ lint
2019/05/14 19:38:37 unknown architecture wasm
pkg/db/stub/stub.go:46:6: `readFile` is unused (deadcode)
func readFile(path string) (*os.File, error) {
     ^
Makefile:193: recipe for target 'lint' failed
make: *** [lint] Error 1
2019/05/14 19:38:39 Tests: exit status 2
```

Variants tried:

DB / API | none | GRPC | REST | REST + GRPC | REST + Contract | REST + GRPC + Contract
------------ | ------------- | ------------ | ------------- | ------------ | ------------- | -------------
none       |       OK       |     OK       |     OK        |     OK       |        X      | X
mysql      |      FAIL     |     FAIL     |     FAIL      |     FAIL     |        OK      | OK
postgres  |      FAIL     |    FAIL     |     FAIL       |    FAIL      |        OK      | OK

**Comment by takama** [comment]
Resolved
